POST http://192.168.56.10:8080/events
Content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NDc2ODQzMjEsInVzZXJJZCI6MX0.3W_VGpLFnT3k7FEvcZ_h68bp8rld4cbJ_cwcZk6T0Uc

{
  "name": "Test Event",
  "description": "This is a test event",
  "location": "latitude: 37.7749, longitude: -122.4194",
  "date_time": "2023-10-01T10:00:00Z"
}


